repos:
  # Python 代码格式化
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13
        files: ^apps/api-gateway/

  # Python 代码检查
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^apps/api-gateway/
      - id: ruff-format
        files: ^apps/api-gateway/

  # Python 类型检查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^apps/api-gateway/
        additional_dependencies:
          - types-redis
          - types-requests
        args: [--ignore-missing-imports, --no-strict-optional]

  # JavaScript/TypeScript 格式化
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^apps/web/
        types_or: [javascript, jsx, ts, tsx, json, markdown, yaml]
        args: [--write]

  # ESLint
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd apps/web && npx eslint'
        language: system
        files: ^apps/web/src/.*\.[jt]sx?$
        types: [file]

  # 通用检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.(md|txt)$
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: detect-private-key

  # 提交信息检查
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # 密钥扫描
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package-lock.json

# 配置选项
default_language_version:
  python: python3.13
  node: 20.11.0

fail_fast: false
