name: Backend Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/api-gateway/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/api-gateway/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        working-directory: apps/api-gateway
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -r requirements-dev.txt

      - name: Run ruff
        working-directory: apps/api-gateway
        run: |
          ruff check . --output-format=github

      - name: Run black
        working-directory: apps/api-gateway
        run: |
          black --check .

      - name: Run mypy
        working-directory: apps/api-gateway
        continue-on-error: true
        run: |
          mypy api_gateway --ignore-missing-imports

      - name: Run pytest
        working-directory: apps/api-gateway
        run: |
          pytest --cov=api_gateway --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./apps/api-gateway/coverage.xml
          flags: backend
          name: backend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api-gateway
          file: ./apps/api-gateway/Dockerfile
          push: false
          tags: cxygpt-api-gateway:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
